config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resource :main, only: [:index, :create], controller: 'main'
  resources :pages, :only => :show
  root 'main#index'

  resources :cars, defaults: {format: :json}
  resources :sliders, defaults: {format: :json}

  namespace :dynamic_select do
    get ':brand_id/car_models', to: 'car_models#index', as: 'car_models'
    get ':car_model_id/colors', to: 'car_models#color', as: 'car_colors'
  end

  namespace :admin do
    root 'requests#index'
    resources :requests
    resources :sliders
    resources :brands do
    end
    resources :car_models
    resources :cars

  end

end

app/models/car.rb
class Car < ActiveRecord::Base
  belongs_to :car_model
  has_one :brand, through: :car_model
end

app/controllers/admin/cars_controller.rb
class Admin::CarsController < Admin::AdminController
  before_action :set_car, only: [:show, :edit, :update, :destroy]

  def index
    @cars = Car.all
  end

  def show
  end

  def new
    @car = Car.new
  end

  def edit
  end

  def create
    @car = Car.new(car_params)

    respond_to do |format|
      if @car.save
        format.html { redirect_to({action: :index}, notice: 'Car was successfully created.') }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @car.update(car_params)
        format.html { redirect_to({action: :index}, notice: 'Car was successfully updated.') }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @car.destroy
    respond_to do |format|
      format.html { redirect_to admin_cars_url, notice: 'Car was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_car
      @car = Car.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def car_params
      params.require(:car).permit!
    end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  respond_to :json
  def index
    @cars = Car.joins(car_model: :brand).where(conditions)
    #respond_with( @cars, include: {car_model: {include: :cars}}, :root => true)
    respond_with(@cars, root: true)
  end

  private

  def conditions
    c = {}
    c.merge!(brands:     {id: params[:brand]})                  if params[:brand]
    c.merge!(car_models: {id: params[:model]})                  if params[:model]
    if params[:color] || params[:engine] || params[:transmission]
      c[:cars] = {}
      c[:cars][:color]= params[:color]               if params[:color]
      c[:cars][:engine]= params[:engine]             if params[:engine]
      c[:cars][:transmission] = params[:transmission] if params[:transmission]
    end
    c
  end
end

app/helpers/admin/cars_helper.rb
module Admin::CarsHelper
end

app/views/admin/cars/_form.html.slim
= semantic_form_for [:admin, @car] do |f|
  = f.input :car_model, as: :select, collection: options_for_select(CarModel.all.map{|m| ["#{m.brand.name} #{m.name}", m.id]}, @car.car_model_id)
  = f.input :name
  = f.input :code
  = f.input :color, as: :string
  = f.input :engine
  = f.input :transmission
  
  = f.actions

app/views/admin/cars/edit.html.slim
h2 Редактировать Авто

= render 'form'

= link_to 'Back', admin_car_models_path

app/views/admin/cars/index.html.slim
h2 Авто

.row
  table.table.table-hover
    thead
      tr
        th
        th
        th
        th
        th
        th

    tbody
      - @cars.each do |c|
        tr
          td = c.id
          td = c.name
          td = c.color
          td = c.engine
          td = c.transmission
          td 
            .btn-group
              = link_to edit_admin_car_path(c), class: 'btn btn-sm btn-default' do
                span.glyphicon.glyphicon-pencil
              = link_to [:admin, c], data: {:confirm => 'Are you sure?'}, :method => :delete, class: 'btn btn-sm btn-default' do
                span.glyphicon.glyphicon-trash
  = link_to 'Добавить авто', new_admin_car_path, class: 'btn btn-default'

app/views/admin/cars/new.html.slim
h2 Новое Авто 

= render 'form'

= link_to 'Назад', admin_cars_path, class: 'btn btn-default'