config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resource :main, only: [:index, :create], controller: 'main'
  resources :pages, :only => :show
  root 'main#index'

  resources :cars, defaults: {format: :json}
  resources :sliders, defaults: {format: :json}

  namespace :dynamic_select do
    get ':brand_id/car_models', to: 'car_models#index', as: 'car_models'
    get ':car_model_id/colors', to: 'car_models#color', as: 'car_colors'
  end

  namespace :admin do
    root 'requests#index'
    resources :requests
    resources :sliders
    resources :brands do
    end
    resources :car_models
    resources :cars

  end

end

app/models/brand.rb
class Brand < ActiveRecord::Base
  has_many :car_model
end

app/controllers/admin/brands_controller.rb
class Admin::BrandsController <  Admin::AdminController
  before_action :set_brand, only: [:show, :edit, :update, :destroy]

  # GET /admin/brands
  # GET /admin/brands.json
  def index
    @brands = Brand.all
  end

  # GET /admin/brands/1
  # GET /admin/brands/1.json
  def show
  end

  # GET /admin/brands/new
  def new
    @brand = Brand.new
  end

  # GET /admin/brands/1/edit
  def edit
  end

  # POST /admin/brands
  # POST /admin/brands.json
  def create
    @brand = Brand.new(brand_params)

    respond_to do |format|
      if @brand.save
        format.html { redirect_to({action: :index}, notice: 'Brand was successfully created.') }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /admin/brands/1
  # PATCH/PUT /admin/brands/1.json
  def update
    respond_to do |format|
      if @brand.update(brand_params)
        format.html { redirect_to({action: :index}, notice: 'Brand was successfully updated.') }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /admin/brands/1
  # DELETE /admin/brands/1.json
  def destroy
    @brand.destroy
    respond_to do |format|
      format.html { redirect_to admin_brands_url, notice: 'Brand was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_brand
      @brand = Brand.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def brand_params
      params.require(:brand).permit!
    end
end

app/helpers/admin/brands_helper.rb
module Admin::BrandsHelper
end

app/views/admin/brands/_form.html.slim
= semantic_form_for [:admin, @brand] do |f|
  = f.input :name
  = f.input :code
  = f.actions

app/views/admin/brands/edit.html.slim
h2 Редактировать бренд

= render 'form'

= link_to 'Назад', admin_brands_path

app/views/admin/brands/index.html.slim
h2 Бренды

.row
  table.table.table-hover
    tr
      th ID
      th Name
      th 
    - @brands.each do |s|
      tr
        td= s.id
        td= s.name
        td
          .btn-group
            = link_to edit_admin_brand_path(s), class: 'btn btn-sm btn-default' do
              span.glyphicon.glyphicon-pencil
            = link_to [:admin, s], class: 'btn btn-sm btn-default', data: {confirm: 'Are you sure?'}, :method => :delete do
              span.glyphicon.glyphicon-trash
  = link_to 'Добавить', new_admin_brand_path, class: 'btn btn-default'

app/views/admin/brands/new.html.slim
h2 Новый бренд
= render 'form'

= link_to 'Назад', admin_brands_path, class: 'btn btn-default'