config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resource :main, only: [:index, :create], controller: 'main'
  resources :pages, :only => :show
  root 'main#index'

  resources :cars, defaults: {format: :json}
  resources :sliders, defaults: {format: :json}

  namespace :dynamic_select do
    get ':brand_id/car_models', to: 'car_models#index', as: 'car_models'
    get ':car_model_id/colors', to: 'car_models#color', as: 'car_colors'
  end

  namespace :admin do
    root 'requests#index'
    resources :requests
    resources :sliders
    resources :brands do
    end
    resources :car_models
    resources :cars

  end

end

app/models/car_model.rb
class CarModel < ActiveRecord::Base
  belongs_to :brand
  has_many :cars
end

app/controllers/admin/car_models_controller.rb
class Admin::CarModelsController < Admin::AdminController
  before_action :set_car_model, only: [:show, :edit, :update, :destroy]

  # GET /car_models
  # GET /car_models.json
  def index
    @car_models = CarModel.all
  end

  # GET /car_models/1
  # GET /car_models/1.json
  def show
  end

  # GET /car_models/new
  def new
    @car_model = CarModel.new
  end

  # GET /car_models/1/edit
  def edit
  end

  # POST /car_models
  # POST /car_models.json
  def create
    @car_model = CarModel.new(car_model_params)

    respond_to do |format|
      if @car_model.save
        format.html { redirect_to({action: :index}, notice: 'Car model was successfully created.') }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /car_models/1
  # PATCH/PUT /car_models/1.json
  def update
    respond_to do |format|
      if @car_model.update(car_model_params)
        format.html { redirect_to({action: :index}, notice: 'Car model was successfully updated.') }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /car_models/1
  # DELETE /car_models/1.json
  def destroy
    @car_model.destroy
    respond_to do |format|
      format.html { redirect_to admin_car_models_url, notice: 'Car model was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_car_model
      @car_model = CarModel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def car_model_params
      params.require(:car_model).permit!
    end
end

app/helpers/car_models_helper.rb
module CarModelsHelper
end

app/views/admin/car_models/_form.html.slim
= semantic_form_for [:admin, @car_model] do |f|
  = f.input :name
  = f.input :code
  = f.input :brand, as: :select
  = f.actions

app/views/admin/car_models/edit.html.slim
h2 Редактировать модель

= render 'form'

= link_to 'Back', admin_car_models_path

app/views/admin/car_models/index.html.slim
h2 Модели
.row
  table.table.table-hover
    thead
      tr
        th ID
        th Name
        th Brand
        th 

    tbody
      - @car_models.each do |car_model|
        tr
          td= car_model.id
          td= car_model.name
          td= car_model.brand.name
          td  
            .btn-group
              = link_to edit_admin_car_model_path(car_model), class: 'btn btn-sm btn-default' do
                span.glyphicon.glyphicon-pencil
              = link_to [:admin, car_model], data: {:confirm => 'Are you sure?'}, :method => :delete, class: 'btn btn-sm btn-default' do
                span.glyphicon.glyphicon-trash
  = link_to 'Добавить', new_admin_car_model_path, class: 'btn btn-default'

app/views/admin/car_models/new.html.slim
h2  Новая модель

= render 'form'

= link_to 'Назад', admin_car_models_path, class: 'btn btn-default'