config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resource :main, only: [:index, :create], controller: 'main'
  resources :pages, :only => :show
  root 'main#index'

  resources :cars, defaults: {format: :json}
  resources :sliders, defaults: {format: :json}

  namespace :dynamic_select do
    get ':brand_id/car_models', to: 'car_models#index', as: 'car_models'
    get ':car_model_id/colors', to: 'car_models#color', as: 'car_colors'
  end

  namespace :admin do
    root 'requests#index'
    resources :requests
    resources :sliders
    resources :brands do
    end
    resources :car_models
    resources :cars

  end

end

app/models/brand.rb
class Brand < ActiveRecord::Base
  has_many :car_model
end

app/models/car.rb
class Car < ActiveRecord::Base
  belongs_to :car_model
  has_one :brand, through: :car_model
end

app/models/car_model.rb
class CarModel < ActiveRecord::Base
  belongs_to :brand
  has_many :cars
end

app/models/city.rb
class City < ActiveRecord::Base
end

app/models/request.rb
class Request < ActiveRecord::Base
end

app/models/slider.rb
class Slider < ActiveRecord::Base
  has_attached_file :picture, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :picture, :content_type => /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin/admin_controller.rb
class Admin::AdminController < ApplicationController
  before_action :authenticate_user!
  layout 'admin'
end

app/controllers/admin/brands_controller.rb
class Admin::BrandsController <  Admin::AdminController
  before_action :set_brand, only: [:show, :edit, :update, :destroy]

  # GET /admin/brands
  # GET /admin/brands.json
  def index
    @brands = Brand.all
  end

  # GET /admin/brands/1
  # GET /admin/brands/1.json
  def show
  end

  # GET /admin/brands/new
  def new
    @brand = Brand.new
  end

  # GET /admin/brands/1/edit
  def edit
  end

  # POST /admin/brands
  # POST /admin/brands.json
  def create
    @brand = Brand.new(brand_params)

    respond_to do |format|
      if @brand.save
        format.html { redirect_to({action: :index}, notice: 'Brand was successfully created.') }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /admin/brands/1
  # PATCH/PUT /admin/brands/1.json
  def update
    respond_to do |format|
      if @brand.update(brand_params)
        format.html { redirect_to({action: :index}, notice: 'Brand was successfully updated.') }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /admin/brands/1
  # DELETE /admin/brands/1.json
  def destroy
    @brand.destroy
    respond_to do |format|
      format.html { redirect_to admin_brands_url, notice: 'Brand was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_brand
      @brand = Brand.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def brand_params
      params.require(:brand).permit!
    end
end

app/controllers/admin/cars_controller.rb
class Admin::CarsController < Admin::AdminController
  before_action :set_car, only: [:show, :edit, :update, :destroy]

  def index
    @cars = Car.all
  end

  def show
  end

  def new
    @car = Car.new
  end

  def edit
  end

  def create
    @car = Car.new(car_params)

    respond_to do |format|
      if @car.save
        format.html { redirect_to({action: :index}, notice: 'Car was successfully created.') }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @car.update(car_params)
        format.html { redirect_to({action: :index}, notice: 'Car was successfully updated.') }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @car.destroy
    respond_to do |format|
      format.html { redirect_to admin_cars_url, notice: 'Car was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_car
      @car = Car.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def car_params
      params.require(:car).permit!
    end
end

app/controllers/admin/sliders_controller.rb
class Admin::SlidersController < Admin::AdminController

  before_action :set_slider, only: [:show, :edit, :update, :destroy]

  def index
    @sliders = Slider.all
  end

  def new
    @slider = Slider.new
  end

  def create
    @slider = Slider.new(slider_params)
    if @slider.save
      redirect_to action: :index
    else
      render "new"
    end
  end

  def show
  
  end

  def edit

  end

  def update
    if @slider.update(slider_params)
      redirect_to action: :index
    else
      render :edit
    end
  end

  def destroy
    @slider.destroy
    redirect_to action: 'index'
  end

  private

  def set_slider
    @slider = Slider.find(params[:id])
  end

  def slider_params
    params.require(:slider).permit!
  end
end

app/controllers/application_controller.rb
# encoding: utf-8
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  #protect_from_forgery with: :exception
  before_action :all_cities
  
  def all_cities
    @cities = City.all.map(&:name)
    @current_city = @cities.first
    city = Ipgeobase.lookup(request.remote_ip).city rescue nil
    if city.present?
      @cities.push(city).uniq!
      @current_city = city
    end
  end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  respond_to :json
  def index
    @cars = Car.joins(car_model: :brand).where(conditions)
    #respond_with( @cars, include: {car_model: {include: :cars}}, :root => true)
    respond_with(@cars, root: true)
  end

  private

  def conditions
    c = {}
    c.merge!(brands:     {id: params[:brand]})                  if params[:brand]
    c.merge!(car_models: {id: params[:model]})                  if params[:model]
    if params[:color] || params[:engine] || params[:transmission]
      c[:cars] = {}
      c[:cars][:color]= params[:color]               if params[:color]
      c[:cars][:engine]= params[:engine]             if params[:engine]
      c[:cars][:transmission] = params[:transmission] if params[:transmission]
    end
    c
  end
end

app/controllers/main_controller.rb
#encoding: utf-8
class MainController < ApplicationController
  def index
  end
  def create
    notify_admin
    Request.create(main_params)
    redirect_to(root_path, notice: 'Ваша заявка принята. Спасибо!')
  end

  private
  
  def notify_admin
    params[:model] = CarModel.find_by_id(params[:model]).try(:name)
    params['brand'] = Brand.find_by_id(params['brand']).try(:name)
    FormNotifier.request_email(params).deliver
  end

  def main_params
    params.permit(:name, :surname, :city, :email, :brand, :model, :color, :engine, :transmission, :flexible)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  PAGES = [:agreement, :privacy, :help, :contact]

  def show
    @page = params[:id].to_sym rescue nil

    redirect_to root_url and return unless PagesController::PAGES.include?(@page)

    #@contact = Contact.new(params[:contact]) if @page == :contact

    render :file => "pages/#{@page}"
  end
end

app/controllers/sliders_controller.rb
class SlidersController < ApplicationController
  respond_to :json
  def index
    @sliders = Slider.all
    respond_with @sliders
  end
end

app/helpers/admin/brands_helper.rb
module Admin::BrandsHelper
end

app/helpers/admin/cars_helper.rb
module Admin::CarsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/car_models_helper.rb
module CarModelsHelper
end

app/views/form_notifier/request_email.html.slim
h3
  |Новая заявка
div
  = "Имя: #{@form['name']} #{@form['surname']}"
div
  = "Email: #{@form['email']}"
div
  = "Город: #{@form['city']}"
p
div
  = "Марка: #{@form['brand']}"
div
  = "Модель: #{@form['model']}"
div
  = "Цвет: #{@form['color']}"
div
  = "Двигатель: #{@form['engine']}"
div
  = "Коробка: #{@form['transmission']}"

app/views/layouts/admin.html.slim
doctype html
html lang="en" 
  head
    meta charset="utf-8" 
    meta content="IE=edge" http-equiv="X-UA-Compatible" 
    meta content="width=device-width, initial-scale=1" name="viewport" 
    meta content="" name="description" 
    meta content="" name="author" 
    title Admin
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    /! Fixed navbar
    .navbar.navbar-default.navbar-static-top role="navigation" 
      .container
        .navbar-header
          button.navbar-toggle data-target=".navbar-collapse" data-toggle="collapse" type="button" 
            span.sr-only Toggle navigation
            span.icon-bar
            span.icon-bar
            span.icon-bar
          .navbar-brand
        .navbar-collapse.collapse
          ul.nav.navbar-nav
            li
              = link_to('Заявки', admin_root_path)
            li
              = link_to('Слайды', admin_sliders_path)
            li
              = link_to('Бренды', admin_brands_path)
            li
              = link_to('Марки', admin_car_models_path)
            li
              = link_to('Авто', admin_cars_path)
    .container
      - if notice
        p.alert.alert-success= notice
      - if alert
        p.alert.alert-danger= alert
      = yield
    /! /container

app/views/layouts/application.html.slim
doctype html
html
  head
    title Carzone
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
body
  #wrapper
    .navbar.navbar-default.navbar-static-top role="navigation" 
      .container
        .navbar-header
          button.navbar-toggle data-target=".navbar-collapse" data-toggle="collapse" type="button" 
            span.sr-only Toggle navigation
            span.icon-bar
            span.icon-bar
            span.icon-bar
          /.navbar-brand
          =link_to image_tag('logo.png'), root_path
        .navbar-collapse.collapse
          form.navbar-form.navbar-right.city-form role="form"
            .form-group
              select#cityselect.form-control
                = options_for_select(@cities, @current_city)
    .container
      .starter-template
        - if notice
          p.alert.alert-success= notice
        - if alert
          p.alert.alert-danger= alert
        = yield
    .page-buffer
  .footer
    .container
      p.text-center
        =link_to 'Правила', page_path('agreement')
        ||
        =link_to 'Обратная связь', page_path('contact')
      p.text-center
        |© Copyright 2014 CARZONE CO.,LTD. All rights reserved.

app/views/pages/agreement.html.slim
.col-md-10.col-md-offset-1
  .spacer
  .panel.panel-default
    .panel-body.text-left
      h3 Правила использования Пользователями Сайта carz.io
      h4 1. Общие положения
      p 1.1. Настоящее Соглашение (далее - «Соглашение») является договором-офертой, т.е. адресованным конкретному лицу (Пользователю) предложением, которое выражает намерение Организатора считать себя заключившим Договор с Пользователем.
      p 1.2. Организатор предлагает Пользователю Услуги по использованию Сайта и его сервисов на условиях, являющихся предметом настоящего Соглашения. Условия настоящего Соглашения разработаны Организатором и определяют условия использования Сайта, а также права и обязанности его Пользователей и Организатора. Условия Соглашения распространяются также на отношения, связанные с правами и интересами третьих лиц, как являющихся Пользователями Сайта (например, Партнеров), так и не являющихся таковыми, но чьи права могут быть затронуты в результате действий Пользователей Сайта.
      p  1.3. Настоящая оферта регулируется следующими правовыми нормами: в соответствии с п. 2 ст. 432 Гражданского Кодекса РФ (ГК РФ) «договор заключается посредством направления оферты (предложения заключить договор) одной из сторон и ее акцепта (принятия предложения) другой стороной»; в соответствии с п. 1 ст. 433 ГК РФ «Договор признается заключенным в момент получения лицом, направившим оферту, ее акцепта»; в соответствии с п. 2 ст. 434 ГК РФ «договор в письменной форме может быть заключен путем … обмена документами посредством почтовой, телеграфной, телетайпной, телефонной, электронной или иной связи, позволяющей достоверно установить, что документ исходит от стороны по договору»; в соответствии с п.3. ст. 434 ГК РФ письменная форма договора считается соблюденной, если письменное предложение заключить договор принято в порядке, предусмотренном пунктом 3 статьи 438 настоящего Кодекса»; в соответствии с п. 3 ст. 438 ГК РФ «Совершение лицом, получившим оферту, в срок, установленный для ее акцепта, действий по выполнению указанных в ней условий договора (отгрузка товаров, предоставление услуг, выполнение работ, уплата соответствующей суммы и т.п.) считается акцептом, если иное не предусмотрено законом, иными правовыми актами или не указано в оферте».
      p  1.4. Пользователь обязан полностью ознакомиться с условиями настоящего Соглашения до момента регистрации на Сайте. Регистрация Пользователя на Сайте означает полное и безоговорочное принятие Пользователем Условий настоящего Соглашения (акцептом настоящей оферты в соответствии со статьей 438 ГК РФ).
      p  1.5. Условия настоящего Соглашения могут быть изменены и/или дополнены Организатором в одностороннем порядке без какого-либо специального уведомления. Настоящее Соглашение является открытым и общедоступным документом. Действующая редакция Соглашения доступна для ознакомления по адресу: carz.io Организатор рекомендует Пользователям регулярно проверять условия настоящего Соглашения на предмет их изменения и/или дополнения. Продолжение использования Сайта Пользователем после внесения изменений/дополнений в условия настоящего Соглашения означает принятие и согласие Пользователя с такими изменениями/дополнениями.
      h4 2. Статус Сайта carz.io
      p 2.1. Сайт carz.io является интернет-ресурсом и представляет собой совокупность информации и программ для ЭВМ, содержащейся в информационной системе, обеспечивающей доступность такой информации в сети Интернет по адресу: carz.io
      p  2.2. Все права на Сайт в целом и на использование сетевого адреса (доменного имени) carz.io принадлежат Организатору. Последний предоставляет доступ к Сайту всем заинтересованным лицам в соответствии с условиями настоящего Соглашения и действующим законодательством Российской Федерации.
      p  3. Пользование сайтом и статус Пользователя
      p  3.1. Пользование сайтом является бесплатным и добровольным. Организатор не взимает с Пользователей платы за пользование сервисами Сайта.
      p  3.2. Пользователями Сайта являются физические лица, достигшие 18 лет, а также юридические лица, обратившиеся к информационным материалам и сервисам Организатора через своего представителя, обладающего соответствующими полномочиями.
      p  3.3. При формировании запроса на Сайте Пользователь обязан указать необходимую достоверную и актуальную контактную информацию, для формирования индивидуального решения для каждого Пользователя.
      p  3.4. Пользователь несет ответственность за достоверность, актуальность, полноту и соответствие законодательству Российской Федерации предоставленной при регистрации формации и ее чистоту от претензий третьих лиц.
      p  3.5. При формировании запроса Пользователь соглашается с настоящими Правилами и принимает на себя указанные в них права и обязанности, связанные с использованием и функционированием Сайта.
      p  3.6. После успешного формирования запроса Пользователя на Сайте Организация принимает на себя права и обязанности перед Пользователем, указанные в настоящих Правилах.
      p  3.7. Принимая условия настоящего Соглашения путем запроса на Сайте, Пользователь заявляет, что настоящим делает сообщаемые им персональные данные общедоступными, и дает Организатору свое согласие на обработку им его персональных данных, предоставленных при осуществлении запроса. Обработка персональных данных Пользователя осуществляется в соответствии с законодательством Российской Федерации. Оператор обрабатывает персональные данные Пользователя в целях исполнения Оператором принятых на себя обязательств в соответствии с настоящим Соглашением. Оператор Сайта принимает все необходимые меры для защиты персональных данных Пользователя от неправомерного доступа, изменения, раскрытия или уничтожения. Оператор предоставляет доступ к персональным данным Пользователя только тем работникам, подрядчикам и агентам Оператора, которым эта информация необходима для обеспечения функционирования Сайта и предоставления Услуг Пользователю. Администрация Сайта вправе использовать предоставленную Пользователем информацию, в том числе персональные данные, в целях обеспечения соблюдения требований действующего законодательства Российской Федерации (в том числе в целях предупреждения и/или пресечения незаконных и/или противоправных действий Пользователей). Раскрытие предоставленной Пользователем информации может быть произведено лишь в соответствии с действующим законодательством Российской Федерации по требованию суда, правоохранительных органов, а равно в иных предусмотренных законодательством Российской Федерации случаях.
      h4 4. Права и обязанности Пользователя
      p 4.1. При пользовании Услугами Сайта Пользователь обязан:
      p  4.1.1. соблюдать положения действующего законодательства Российской Федерации, настоящего Соглашения и иных специальных документов Организатора Сайта;
      p  4.1.2. предоставлять при формировании запроса достоверные, полные и актуальные данные, следить за их актуализацией;
      p  4.1.3. хранить в тайне и не предоставлять другим Пользователям и третьим лицам ставшие ему известными в результате использования Сайта данные (включая, но не ограничиваясь, персональными данными, паспортными данными, банковской информацией) других Пользователей, Партнеров и любых третьих лиц без получения соответствующего предварительного разрешения последних.
      p  4.2. Пользователю при использовании Сайта запрещается:
      p  4.2.1. Формировать запрос от  Пользователя от имени или вместо другого лица («фальшивый аккаунт»);
      p  4.2.2. незаконно загружать, хранить, публиковать, распространять и предоставлять доступ или иным образом использовать интеллектуальную собственность Пользователей, Партнеров и иных третьих лиц;
      p  4.2.3. использовать программное обеспечение и осуществлять действия, направленные на нарушение нормального функционирования Сайта и его сервисов или персональных страниц Пользователей и Партнеров;
      p  4.2.4. загружать, хранить, публиковать, распространять и предоставлять доступ или иным образом использовать вирусы, трояны и другие вредоносные программы;
      p  4.2.5. использовать без специального на то разрешения Организатора автоматизированные скрипты (программы) для сбора информации на Сайте и(или) взаимодействия с Сайтом и его сервисами;
      p  4.2.6. осуществлять незаконные сбор и обработку персональных данных других лиц;
      p  4.2.7. осуществлять (пытаться получить) доступ к каким-либо Услугам иным способом, кроме как через интерфейс, предоставленный Организатором Сайта, за исключением случаев, когда такие действия были прямо разрешены Пользователю в соответствии с отдельным соглашением с Организатором;
      p  4.2.8. воспроизводить, дублировать, копировать, продавать, осуществлять торговые операции и перепродавать Услуги для каких-либо целей, за исключением случаев, когда такие действия были прямо разрешены Пользователю в соответствии с условиями отдельного соглашения с Организатором;
      p  4.2.9. размещать коммерческую и политическую рекламу вне специальных разделов Сайта, установленных Организатором. Приобретение Пользователем платных услуг на Сайте осуществляется в порядке, установленном в специальных документах Организатора, размещенных на Сайте.
      p  4.3. Пользователь несет личную ответственность за любую информацию, которую размещает на Сайте, сообщает другим Пользователям, а также за любые взаимодействия с другими Пользователями и Партнерами, осуществляемые на свой риск.
      p  4.4. В случае несогласия Пользователя с настоящим Соглашением или его обновлениями, Пользователь обязан отказаться от его использования путем обращение в службу поддержки по электронному адресу clients@carz.io
      h4 5. Условия сотрудничества. Права и обязанности Организатора
      p 5.1. Стороны настоящим выражают свое понимание, что Организатор не владеет и не управляет автотранспортными средствами, предложения по которым публикуются Партнером. Сайт carz.ioявляется площадкой для размещения предложений о покупке/продаже автотранспортных средств Партнерами, которые единолично, без участия Организатора распоряжаются указанными автотранспортными средствами. Организатор не принимает участия в сделках, но дает Партнеру (автодилеру) и Пользователям (покупателю) возможность заключать сделки напрямую.
      p  5.2. Акцептуя настоящую Оферту, Пользователь подтверждает, что Организатор не несет ответственности за любую часть сделки по покупке автотранспортного средства, за актуальность и достоверность информации в предложениях автодилера.
      p  5.3. Организатор не несет ответственности за актуальность и достоверности предложений автодилеров, размещенных на Сайте, в том числе достоверность в части характеристик транспортных средств и т.п.
      p  5.4. Организатор не несет ответственность за состояние автотранспортных средств, а равно за соблюдение законов, правил и положений, которые могут быть применимы к любому автотранспортному средству в любой юрисдикции.
      p  5.5. С момента регистрации Пользователя на Сайте Организатор выступает исключительно как посредник между Партнером и Пользователем, публикуя детали Заявки на Сайте и по запросу Пользователя предоставляя контактные данные Партнера.
      p  5.6. Организатор не несет ответственности за любые задержки, возникшие из-за временной или частичной поломки, ремонта, усовершенствования или поддержки Сайта, неаккуратную, недостоверную или ложную информацию, а также недоставку информации.
      p  5.7. Администрация Сайта имеет право направлять Пользователю информацию о развитии Сайта и его сервисов, а также рекламировать собственную деятельность и услуги, путем передачи смс-сообщения или же путем прямой рассылки на электронный адрес Пользователя
      p  5.8. Любые претензии Пользователя, связанные с автотранспортными средствами, их покупкой и т.п. действиями и информацией, находящимися за границами ответственности Организатора, подлежат предъявлению соответствующим лицам – другим Пользователям и/или Партнерам и/или иным третьим лицам, действия/бездействие которых повлекло за собой возникновение таких претензий у Пользователя.
      h4 6. Условия об интеллектуальных правах
      p 6.1. Все объекты, размещенные на Сайте, в том числе элементы дизайна, текст, графические изображения, иллюстрации, видео, скрипты, программы, музыка, звуки и другие объекты и их подборки (далее - Контент), являются объектами исключительных прав Организатора, Партнеров, Пользователей Сайта и других правообладателей, все права на эти объекты защищены.
      p  6.2. Кроме случаев, установленных настоящим Соглашением, а также действующим законодательством Российской Федерации, никакой Контент не может быть скопирован (воспроизведен), переработан, распространен, отображен во фрейме, опубликован, скачан, передан, продан или иным способом использован целиком или по частям без предварительного разрешения правообладателя, кроме случаев, когда правообладатель явным образом выразил свое согласие на свободное использование Контента любым лицом.
      h4 7. Заключительные положения
      p 7.1. Если какое-либо условие настоящего оглашения будет недействительно или неосуществимо в соответствии с действующим законодательством РФ, все остальные условия остаются в силе, а недействительное или неосуществимое условие будет считаться замененным соответствующим действительным, осуществимым условием действующего законодательства РФ, которое наиболее близко соответствует намерению первоначального условия.

app/views/pages/contact.html.slim
.col-md-10.col-md-offset-1
  .spacer
  .panel.panel-default
    .panel-body.text-left
      h3 Обратная связь
      p
        |В случае, если у Вас возникли какие-либо вопросы и предложения, можете написать нам на адрес: 
        = mail_to 'clients@carz.io'
        |. Спасибо!

app/views/pages/help.html.slim
h1 Help

app/views/pages/privacy.html.slim
h1 Privacy